[package]
name = "libp2p-relay"
edition = "2018"
description = "Communications relaying for libp2p"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
bytes = "0.4"
fnv = "1.0"
futures = "0.1"
libp2p-core = { version = "0.20.1", path = "../../core" }
log = "0.4"
protobuf = "2.0.2"
rand = "0.6"
smallvec = "0.6.9"
tokio-codec = "0.1"
tokio-io = "0.1"
unsigned-varint = { version = "0.2.1", features = ["codec"] }
void = "1.0"
